class Solution {
  /*
   * Complexity: O(n)
   * Space: O(n)
   */
public:
    int nthUglyNumber(int n) {
        // pointer of each prime
        // each ugly numbers are generated by the product of the primes and the previous ugly numbers
        int p2 = 0, p3 = 0, p5 = 0;
        vector<int>dp(n);
        dp[0] = 1;
        
        for(int i = 1; i < n; ++i){
            // 3 smallest number that can be generated using these three primes
            dp[i] = min(dp[p2] * 2, min(dp[p3]*3, dp[p5]*5));
            if(dp[i] == dp[p2] * 2) ++p2;
            if(dp[i] == dp[p3] * 3) ++p3;
            if(dp[i] == dp[p5] * 5) ++p5;
        }
        return dp[n-1];
    }
};
